# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clicked', models.BooleanField(default=False)),
            ],
        ),
    ]
