# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 10:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('angularexample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='updateTimestamp',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 28, 10, 28, 5, 413554, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
