# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angularexample', '0002_element_updatetimestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='updateTimestamp',
            new_name='serverUpdatedLast',
        ),
    ]
