# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angularexample', '0003_auto_20160128_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='serverUpdatedLast',
            new_name='serverTimestamp',
        ),
    ]
