# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('angularexample', '0004_auto_20160128_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
