# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angularexample', '0005_auto_20160202_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='serverTimestamp',
            new_name='timestamp',
        ),
    ]
