# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angularexample', '0006_auto_20160209_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='name',
            new_name='text',
        ),
    ]
