# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angularexample', '0007_auto_20160211_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
